# Generated by Django 3.2.8 on 2021-12-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='Latitud',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='envio',
            name='Longitud',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
