# Generated by Django 3.2.8 on 2021-12-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0002_auto_20211202_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='costo',
            field=models.FloatField(null=True),
        ),
    ]
