# Generated by Django 3.2.8 on 2021-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0003_alter_envio_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='costo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
