# Generated by Django 3.2.8 on 2021-11-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('numero_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('numero_grupo', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_funcionario',
            fields=[
                ('documento_funcionario', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_funcionario', models.TextField(max_length=40)),
                ('apellido_funcionario', models.TextField(max_length=40)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_empresa',
            fields=[
                ('rut', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('razon_social', models.TextField(max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modficado', models.DateTimeField(auto_now=True)),
                ('entidad_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.entidad', verbose_name='numero_entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_cliente',
            fields=[
                ('nombre_usuario', models.TextField(max_length=40)),
                ('apellido_usuario', models.TextField(max_length=40)),
                ('documento_usuario', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modficado', models.DateTimeField(auto_now=True)),
                ('entidad_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.entidad', verbose_name='numero_entidad')),
            ],
        ),
    ]
