# Generated by Django 3.2.9 on 2021-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='cliente',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='empresa',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
