# Generated by Django 3.2.9 on 2021-12-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20211203_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='cliente',
        ),
    ]
