# Generated by Django 3.2.9 on 2021-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_entidad_numero_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='numero_grupo',
            field=models.CharField(choices=[('F', 'Fijo'), ('P', 'Peso'), ('DP', 'Distancia/Peso')], default='F', max_length=5),
        ),
    ]
